//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. To customize, move logic into AdminDashboardUserControl.cs.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace ComicRentalSystem_14Days.Controls
{
    partial class AdminDashboardUserControl
    {
        #region Component Designer generated code

        private void InitializeComponent()
        {
            outerTable = new TableLayoutPanel();
            lblDashboardTitle = new Label();
            metricsTable = new TableLayoutPanel();
            gbTotalComics = new GroupBox();
            lblTotalComicsValue = new Label();
            gbRentedComics = new GroupBox();
            lblRentedComicsValue = new Label();
            gbAvailableComics = new GroupBox();
            lblAvailableComicsValue = new Label();
            gbActiveMembers = new GroupBox();
            lblActiveMembersValue = new Label();
            outerTable.SuspendLayout();
            metricsTable.SuspendLayout();
            gbTotalComics.SuspendLayout();
            gbRentedComics.SuspendLayout();
            gbAvailableComics.SuspendLayout();
            gbActiveMembers.SuspendLayout();
            SuspendLayout();
            // 
            // outerTable
            // 
            outerTable.ColumnCount = 1;
            outerTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            outerTable.Controls.Add(lblDashboardTitle, 0, 0);
            outerTable.Controls.Add(metricsTable, 0, 1);
            outerTable.Dock = DockStyle.Fill;
            outerTable.Location = new Point(0, 0);
            outerTable.Margin = new Padding(4, 4, 4, 4);
            outerTable.Name = "outerTable";
            outerTable.RowCount = 2;
            outerTable.RowStyles.Add(new RowStyle());
            outerTable.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            outerTable.Size = new Size(771, 507);
            outerTable.TabIndex = 0;
            // 
            // lblDashboardTitle
            // 
            lblDashboardTitle.AutoSize = true;
            lblDashboardTitle.Dock = DockStyle.Fill;
            lblDashboardTitle.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblDashboardTitle.ForeColor = Color.FromArgb(33, 37, 41);
            lblDashboardTitle.Location = new Point(13, 13);
            lblDashboardTitle.Margin = new Padding(13, 13, 0, 13);
            lblDashboardTitle.Name = "lblDashboardTitle";
            lblDashboardTitle.Size = new Size(758, 41);
            lblDashboardTitle.TabIndex = 0;
            lblDashboardTitle.Text = "儀錶板";
            lblDashboardTitle.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // metricsTable
            // 
            metricsTable.ColumnCount = 2;
            metricsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            metricsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            metricsTable.Controls.Add(gbTotalComics, 0, 0);
            metricsTable.Controls.Add(gbRentedComics, 1, 0);
            metricsTable.Controls.Add(gbAvailableComics, 0, 1);
            metricsTable.Controls.Add(gbActiveMembers, 1, 1);
            metricsTable.Dock = DockStyle.Fill;
            metricsTable.Location = new Point(13, 67);
            metricsTable.Margin = new Padding(13, 0, 13, 13);
            metricsTable.Name = "metricsTable";
            metricsTable.RowCount = 2;
            metricsTable.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            metricsTable.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            metricsTable.Size = new Size(745, 427);
            metricsTable.TabIndex = 1;
            // 
            // gbTotalComics
            // 
            gbTotalComics.Controls.Add(lblTotalComicsValue);
            gbTotalComics.Dock = DockStyle.Fill;
            gbTotalComics.Font = new Font("Segoe UI", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            gbTotalComics.ForeColor = Color.FromArgb(52, 58, 64);
            gbTotalComics.Location = new Point(6, 6);
            gbTotalComics.Margin = new Padding(6, 6, 6, 6);
            gbTotalComics.Name = "gbTotalComics";
            gbTotalComics.Padding = new Padding(6, 6, 6, 6);
            gbTotalComics.Size = new Size(360, 201);
            gbTotalComics.TabIndex = 0;
            gbTotalComics.TabStop = false;
            gbTotalComics.Text = "漫畫數量";
            // 
            // lblTotalComicsValue
            // 
            lblTotalComicsValue.Dock = DockStyle.Fill;
            lblTotalComicsValue.Font = new Font("Segoe UI Semibold", 24F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblTotalComicsValue.ForeColor = Color.FromArgb(52, 58, 64);
            lblTotalComicsValue.Location = new Point(6, 29);
            lblTotalComicsValue.Margin = new Padding(4, 0, 4, 0);
            lblTotalComicsValue.Name = "lblTotalComicsValue";
            lblTotalComicsValue.Size = new Size(348, 166);
            lblTotalComicsValue.TabIndex = 0;
            lblTotalComicsValue.Text = "0";
            lblTotalComicsValue.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // gbRentedComics
            // 
            gbRentedComics.Controls.Add(lblRentedComicsValue);
            gbRentedComics.Dock = DockStyle.Fill;
            gbRentedComics.Font = new Font("Segoe UI", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            gbRentedComics.ForeColor = Color.FromArgb(52, 58, 64);
            gbRentedComics.Location = new Point(378, 6);
            gbRentedComics.Margin = new Padding(6, 6, 6, 6);
            gbRentedComics.Name = "gbRentedComics";
            gbRentedComics.Padding = new Padding(6, 6, 6, 6);
            gbRentedComics.Size = new Size(361, 201);
            gbRentedComics.TabIndex = 1;
            gbRentedComics.TabStop = false;
            gbRentedComics.Text = "被租借漫畫數量";
            // 
            // lblRentedComicsValue
            // 
            lblRentedComicsValue.Dock = DockStyle.Fill;
            lblRentedComicsValue.Font = new Font("Segoe UI Semibold", 24F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblRentedComicsValue.ForeColor = Color.FromArgb(52, 58, 64);
            lblRentedComicsValue.Location = new Point(6, 29);
            lblRentedComicsValue.Margin = new Padding(4, 0, 4, 0);
            lblRentedComicsValue.Name = "lblRentedComicsValue";
            lblRentedComicsValue.Size = new Size(349, 166);
            lblRentedComicsValue.TabIndex = 0;
            lblRentedComicsValue.Text = "0";
            lblRentedComicsValue.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // gbAvailableComics
            // 
            gbAvailableComics.Controls.Add(lblAvailableComicsValue);
            gbAvailableComics.Dock = DockStyle.Fill;
            gbAvailableComics.Font = new Font("Segoe UI", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            gbAvailableComics.ForeColor = Color.FromArgb(52, 58, 64);
            gbAvailableComics.Location = new Point(6, 219);
            gbAvailableComics.Margin = new Padding(6, 6, 6, 6);
            gbAvailableComics.Name = "gbAvailableComics";
            gbAvailableComics.Padding = new Padding(6, 6, 6, 6);
            gbAvailableComics.Size = new Size(360, 202);
            gbAvailableComics.TabIndex = 2;
            gbAvailableComics.TabStop = false;
            gbAvailableComics.Text = "可供租借漫畫";
            // 
            // lblAvailableComicsValue
            // 
            lblAvailableComicsValue.Dock = DockStyle.Fill;
            lblAvailableComicsValue.Font = new Font("Segoe UI Semibold", 24F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblAvailableComicsValue.ForeColor = Color.FromArgb(52, 58, 64);
            lblAvailableComicsValue.Location = new Point(6, 29);
            lblAvailableComicsValue.Margin = new Padding(4, 0, 4, 0);
            lblAvailableComicsValue.Name = "lblAvailableComicsValue";
            lblAvailableComicsValue.Size = new Size(348, 167);
            lblAvailableComicsValue.TabIndex = 0;
            lblAvailableComicsValue.Text = "0";
            lblAvailableComicsValue.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // gbActiveMembers
            // 
            gbActiveMembers.Controls.Add(lblActiveMembersValue);
            gbActiveMembers.Dock = DockStyle.Fill;
            gbActiveMembers.Font = new Font("Segoe UI", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            gbActiveMembers.ForeColor = Color.FromArgb(52, 58, 64);
            gbActiveMembers.Location = new Point(378, 219);
            gbActiveMembers.Margin = new Padding(6, 6, 6, 6);
            gbActiveMembers.Name = "gbActiveMembers";
            gbActiveMembers.Padding = new Padding(6, 6, 6, 6);
            gbActiveMembers.Size = new Size(361, 202);
            gbActiveMembers.TabIndex = 3;
            gbActiveMembers.TabStop = false;
            gbActiveMembers.Text = "活躍會員";
            // 
            // lblActiveMembersValue
            // 
            lblActiveMembersValue.Dock = DockStyle.Fill;
            lblActiveMembersValue.Font = new Font("Segoe UI Semibold", 24F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblActiveMembersValue.ForeColor = Color.FromArgb(52, 58, 64);
            lblActiveMembersValue.Location = new Point(6, 29);
            lblActiveMembersValue.Margin = new Padding(4, 0, 4, 0);
            lblActiveMembersValue.Name = "lblActiveMembersValue";
            lblActiveMembersValue.Size = new Size(349, 167);
            lblActiveMembersValue.TabIndex = 0;
            lblActiveMembersValue.Text = "0";
            lblActiveMembersValue.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // AdminDashboardUserControl
            // 
            AutoScaleDimensions = new SizeF(9F, 19F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(248, 249, 250);
            Controls.Add(outerTable);
            Margin = new Padding(4, 4, 4, 4);
            Name = "AdminDashboardUserControl";
            Size = new Size(771, 507);
            outerTable.ResumeLayout(false);
            outerTable.PerformLayout();
            metricsTable.ResumeLayout(false);
            gbTotalComics.ResumeLayout(false);
            gbRentedComics.ResumeLayout(false);
            gbAvailableComics.ResumeLayout(false);
            gbActiveMembers.ResumeLayout(false);
            ResumeLayout(false);
        }

        #endregion

        private TableLayoutPanel outerTable;
        private Label lblDashboardTitle;
        private TableLayoutPanel metricsTable;
        private GroupBox gbTotalComics;
        private GroupBox gbRentedComics;
        private GroupBox gbAvailableComics;
        private GroupBox gbActiveMembers;
    }
}
