//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. To customize, move logic into AdminDashboardUserControl.cs.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace ComicRentalSystem_14Days.Controls
{
    partial class AdminDashboardUserControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private IContainer components = null;

        #region Component Designer generated code

        private void InitializeComponent()
        {
            this.components = new Container();

            // (1) 最外層 TableLayoutPanel：兩列、一欄
            var outerTable = new TableLayoutPanel();
            // (2) 裡面再嵌一個 2x2 的 TableLayoutPanel 放四個 GroupBox
            var metricsTable = new TableLayoutPanel();

            // (3) 標題 Label
            var lblDashboardTitle = new Label();

            //
            // lblDashboardTitle (標題)
            //
            lblDashboardTitle.AutoSize = true;
            lblDashboardTitle.Dock = DockStyle.Fill;
            lblDashboardTitle.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblDashboardTitle.ForeColor = Color.FromArgb(33, 37, 41);
            lblDashboardTitle.Text = "Dashboard Overview";
            lblDashboardTitle.TextAlign = ContentAlignment.MiddleLeft;
            lblDashboardTitle.Margin = new Padding(10, 10, 0, 10);

            //
            // outerTable (最外層 TableLayoutPanel)
            //
            outerTable.ColumnCount = 1;
            outerTable.RowCount = 2;
            outerTable.Dock = DockStyle.Fill;
            outerTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            // 第一列放標題，高度自適應
            outerTable.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            // 第二列放 metrics table，剩下所有空間
            outerTable.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            outerTable.Controls.Add(lblDashboardTitle, 0, 0);

            //
            // metricsTable (裡面放 2x2 四個 GroupBox)
            //
            metricsTable.ColumnCount = 2;
            metricsTable.RowCount = 2;
            metricsTable.Dock = DockStyle.Fill;
            // 兩欄平均
            metricsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            metricsTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            // 兩列平均
            metricsTable.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            metricsTable.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            metricsTable.Margin = new Padding(10, 0, 10, 10);

            // 四個 GroupBox 分別放到 metricsTable 裡
            var gbTotalComics = new GroupBox();
            var gbRentedComics = new GroupBox();
            var gbAvailableComics = new GroupBox();
            var gbActiveMembers = new GroupBox();

            // ── 共用的字型 & 顏色 ──
            var groupFont = new Font("Segoe UI", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            var groupForeColor = Color.FromArgb(52, 58, 64);
            var metricValueFont = new Font("Segoe UI Semibold", 24F, FontStyle.Bold, GraphicsUnit.Point, 0);
            var metricValueColor = Color.FromArgb(52, 58, 64);

            // gbTotalComics
            gbTotalComics.Dock = DockStyle.Fill;
            gbTotalComics.Font = groupFont;
            gbTotalComics.ForeColor = groupForeColor;
            gbTotalComics.Text = "Total Comics";
            gbTotalComics.Margin = new Padding(5);
            gbTotalComics.Padding = new Padding(5);
            // 將內部的 Label 放到 GroupBox 裡
            this.lblTotalComicsValue = new Label();
            this.lblTotalComicsValue.Dock = DockStyle.Fill;
            this.lblTotalComicsValue.Font = metricValueFont;
            this.lblTotalComicsValue.ForeColor = metricValueColor;
            this.lblTotalComicsValue.Text = "0";
            this.lblTotalComicsValue.TextAlign = ContentAlignment.MiddleCenter;
            gbTotalComics.Controls.Add(this.lblTotalComicsValue);

            // gbRentedComics
            gbRentedComics.Dock = DockStyle.Fill;
            gbRentedComics.Font = groupFont;
            gbRentedComics.ForeColor = groupForeColor;
            gbRentedComics.Text = "Rented Comics";
            gbRentedComics.Margin = new Padding(5);
            gbRentedComics.Padding = new Padding(5);
            this.lblRentedComicsValue = new Label();
            this.lblRentedComicsValue.Dock = DockStyle.Fill;
            this.lblRentedComicsValue.Font = metricValueFont;
            this.lblRentedComicsValue.ForeColor = metricValueColor;
            this.lblRentedComicsValue.Text = "0";
            this.lblRentedComicsValue.TextAlign = ContentAlignment.MiddleCenter;
            gbRentedComics.Controls.Add(this.lblRentedComicsValue);

            // gbAvailableComics
            gbAvailableComics.Dock = DockStyle.Fill;
            gbAvailableComics.Font = groupFont;
            gbAvailableComics.ForeColor = groupForeColor;
            gbAvailableComics.Text = "Available Comics";
            gbAvailableComics.Margin = new Padding(5);
            gbAvailableComics.Padding = new Padding(5);
            this.lblAvailableComicsValue = new Label();
            this.lblAvailableComicsValue.Dock = DockStyle.Fill;
            this.lblAvailableComicsValue.Font = metricValueFont;
            this.lblAvailableComicsValue.ForeColor = metricValueColor;
            this.lblAvailableComicsValue.Text = "0";
            this.lblAvailableComicsValue.TextAlign = ContentAlignment.MiddleCenter;
            gbAvailableComics.Controls.Add(this.lblAvailableComicsValue);

            // gbActiveMembers
            gbActiveMembers.Dock = DockStyle.Fill;
            gbActiveMembers.Font = groupFont;
            gbActiveMembers.ForeColor = groupForeColor;
            gbActiveMembers.Text = "Active Members";
            gbActiveMembers.Margin = new Padding(5);
            gbActiveMembers.Padding = new Padding(5);
            this.lblActiveMembersValue = new Label();
            this.lblActiveMembersValue.Dock = DockStyle.Fill;
            this.lblActiveMembersValue.Font = metricValueFont;
            this.lblActiveMembersValue.ForeColor = metricValueColor;
            this.lblActiveMembersValue.Text = "0";
            this.lblActiveMembersValue.TextAlign = ContentAlignment.MiddleCenter;
            gbActiveMembers.Controls.Add(this.lblActiveMembersValue);

            // 把四個 GroupBox 放到 2x2 的 metricsTable 裡
            metricsTable.Controls.Add(gbTotalComics, 0, 0);
            metricsTable.Controls.Add(gbRentedComics, 1, 0);
            metricsTable.Controls.Add(gbAvailableComics, 0, 1);
            metricsTable.Controls.Add(gbActiveMembers, 1, 1);

            // 將 metricsTable 放到 outerTable 的第二列
            outerTable.Controls.Add(metricsTable, 0, 1);

            //
            // AdminDashboardUserControl (本身的屬性)
            //
            this.AutoScaleDimensions = new SizeF(7F, 15F);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.FromArgb(248, 249, 250);
            this.Controls.Add(outerTable);
            this.Padding = new Padding(0);
            this.Name = "AdminDashboardUserControl";
            this.Size = new Size(600, 400); // 只是一個預設值，實際會被 Dock=Fill 完全撐開

            // 最後呼叫 ResumeLayout
            outerTable.ResumeLayout(false);
            outerTable.PerformLayout();
            metricsTable.ResumeLayout(false);
            gbTotalComics.ResumeLayout(false);
            gbRentedComics.ResumeLayout(false);
            gbAvailableComics.ResumeLayout(false);
            gbActiveMembers.ResumeLayout(false);
            this.ResumeLayout(false);
        }

        #endregion
    }
}
